version: 2.1

references:
  stage_param: &stage_param
    type: enum
    enum: [dev, prod]

orbs:
  aws-cli: circleci/aws-cli@1.3.0
  terraform: circleci/terraform@1.0.1

executors:
  terraform: terraform/default

commands:
  prepare_tf:
    parameters:
      stage: *stage_param
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION
      - terraform/init:
          path: ~/project/.aws/live/<< parameters.stage >>

jobs:
  apply_plan:
    executor:
      name: terraform
      image: zenika/terraform-aws-cli
    parameters:
      stage: *stage_param
    steps:
      - prepare_tf:
          stage: << parameters.stage >>
      - run:
          command: terraform apply -auto-approve
          working_directory: ~/project/.aws/live/<< parameters.stage >>

  validate_plan:
    executor:
      name: terraform
      image: zenika/terraform-aws-cli
    parameters:
      stage: *stage_param
    steps:
      - prepare_tf:
          stage: << parameters.stage >>
      - terraform/plan:
          path: ~/project/.aws/live/<< parameters.stage >>

workflows:
  deploy_dev:
    jobs:
      - validate_plan:
          context: deploy.dev
          name: validate_plan_dev
          stage: dev
          filters:
            branches:
              only:
                - master
      - apply_plan:
          context: deploy.dev
          name: apply_plan_dev
          stage: dev
          requires:
            - validate_plan_dev
  deploy_prod:
    jobs:
      - validate_plan:
          context: deploy.dev
          name: validate_plan_prod
          stage: prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /prod-*/
      - apply_plan:
          context: deploy.dev
          name: apply_plan_prod
          stage: prod
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /prod-*/
          requires:
            - validate_plan_prod
